### ISSUE TITLE
node events object dont have hasOwnProperty function

### ISSUE THREAD

**Issue by NatureFeng** [tracker1/safe-clone-deep#3]
this is example:

```
const EventEmitter = require('events'); 
const emit = new EventEmitter(); 
console.log(emit._events.hasOwnProperty) // undefined
```

when i clone eventEmitter object with safe-clone-deep，i got this error。
```
obj.hasOwnProperty is not a function.
```

my node version is v6.9.1
becase emit._events's prototype is undefined in the new version in node.

i found it in node v6.0.0 changelog.
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#notable-changes-19
The EventEmitter.prototype._events object no longer inherits from Object.prototype.

i think maybe you need consider some object that dont have hasOwnProperty function.

**Comment by tracker1** [comment]
Wild...  :-(

Will take a look at this.

**Comment by tracker1** [comment]
@NatureFeng You may want to look at [fclone](https://www.npmjs.com/package/fclone), which was loosely based on mine to begin with, and has a couple added features (typed arrays, etc).  It's what I've been using for a while now...

**Comment by NatureFeng** [comment]
ok. i think fclone is fine.
If you think this feature does not need to be considered, you can close the issue and my PR.
thank you for your reply~

**Comment by tracker1** [comment]
fixed and in npm
